#!/bin/env python

"""continuous scan macros"""

__all__ = ["cscan_zebra_xia", "cscan_zebra_xia_senv"]

import PyTango
from sardana.macroserver.macro import *
from sardana.macroserver.macro import macro
import json
import time
import pytz
import datetime
import numpy


class cscan_zebra_xia(Macro):
    """Perfoms a continuous scan with the zebra triggering the xia"""

    param_def = [
       ['motor',            Type.Motor,   None, 'Motor to move'],
       ['start_pos',        Type.Float,   None, 'Scan start position'],
       ['final_pos',        Type.Float,   None, 'Scan final position'],
       ['nb_triggers',      Type.Integer, None, 'Nb of triggers generated by the zebra'],
       ['trigger_interval', Type.Float,   None, 'Time between consecutive triggers']
    ]

    result_def = [ [ "result", Type.String, None, "the cscan object" ]]

    def run(self, motor, start_pos, final_pos, nb_triggers, trigger_interval):

        zebra_device_name       = self.getEnv('ZebraDevice')
        self.output("Using zebra device " + zebra_device_name)
#        mcs_device_name         = self.getEnv('MCSDevice')
        xia_device_name         = self.getEnv('XIADevice')
        self.output("Using xia device " + xia_device_name)
        nexusconfig_device_name = self.getEnv('NeXusConfigDevice')   # class XMLConfigServer
        nexuswriter_device_name = self.getEnv('NeXusWriterDevice') # class TangoDataServer
        zebra_device       = PyTango.DeviceProxy(zebra_device_name)
 #       mcs_device         = PyTango.DeviceProxy(mcs_device_name)
        xia_device         = PyTango.DeviceProxy(xia_device_name)
        motor_device       = PyTango.DeviceProxy(motor.getName())
        self.nexusconfig_device = PyTango.DeviceProxy(nexusconfig_device_name)
        self.nexuswriter_device = PyTango.DeviceProxy(nexuswriter_device_name)

        time.sleep(5)

        self._openNxFile()
        # Set the zebra device

        zebra_device.NbTriggers = nb_triggers
        zebra_device.TriggerInterval = trigger_interval
    
        # Set MCS
        
#        mcs_device.NbAcquisitions = 0 # Continuous mode
#        mcs_device.NbChannels     = nb_mcs_channels

        # Clear and setup mcs

#        mcs_device.ClearSetupMCS()

        # Set XIA

        xia_device.MappingMode = 1
        xia_device.GateMaster = 1
        xia_device.NumberMcaChannels = 2048
        xia_device.NumMapPixels = nb_triggers
#        if nb_triggers%2 == 0:
#          xia_device.NumMapPixelsPerBuffer = nb_triggers/2
#        else:
#            xia_device.NumMapPixelsPerBuffer = (nb_triggers + 1)/2
        xia_device.NumMapPixelsPerBuffer = -1
        xia_device.MaskMapChannels = 1 # change if one wants to work with more XIA channels

        nb_xia_channels = xia_device.NumberMcaChannels

        xia_device.StartMapping()

        # Compute motor slewrate for the continuous scan

        old_slewrate = motor_device.Velocity

        scan_slewrate = abs(final_pos - start_pos)/(trigger_interval * (nb_triggers - 1))

        motor_device.Velocity = scan_slewrate 

        # Move motor to start position minus an offset

        if start_pos < final_pos:
            pos_offset = 0.1
        else:
            pos_offset = -0.1

        motor_device.Position = start_pos - pos_offset
        
        while motor_device.State() == PyTango.DevState.MOVING:
            time.sleep(1)

        # Start motor movement to final position (the macro mv can not be used because it blocks)
        
        motor_device.Position = final_pos + pos_offset

        # Check when the motor is in the start_position for starting the trigger

        while(motor_device.Position < start_pos):
            time.sleep(0.001)

        

        # Store starttime

        amsterdam = pytz.timezone('Europe/Amsterdam')
        self.starttime = amsterdam.localize(datetime.datetime.now())
            

        # Start zebra triggering 

        zebra_device.Arm = 1

        # Check when the triggering is done

        while zebra_device.State() == PyTango.DevState.MOVING:
            time.sleep(1)
        
        # Check that the XIA is done

        while xia_device.State() == PyTango.DevState.MOVING:
            time.sleep(1)

        # Reset motor slewrate

        motor_device.Velocity = old_slewrate

        # Read MCS

#        mcs_device.ReadMCS()

        # MCS Data

#        nb_mcs_taken_triggers = mcs_device.AcquiredTriggers
#        nb_mcs_channels = mcs_device.NbChannels
#        mcs_data = mcs_device.CountsArray
  

        # Zebra encoder Data

#        self.zebra_data = zebra_device.EncoderSpectrum

            
        # Open the nexus file for saving data

        self._openNxFile()
        self._openNxEntry(motor.getName(), start_pos, final_pos, nb_triggers, trigger_interval, nb_xia_channels)

        # Close NeXus file

        self._closeNxEntry()
        self._closeNxFile()

        result = "Esto es un test"
        return result 

    def _openNxFile(self):
        cscan_id = self.getEnv('CScanID')
        fileNameNx = self.getEnv('CScanFileName') + "_" + str(cscan_id) + ".h5"
        self.setEnv("CScanID", cscan_id + 1)
        self.nexuswriter_device.Init()
        self.nexuswriter_device.FileName = str(fileNameNx)
        self.nexuswriter_device.OpenFile()
        return 1

    def _openNxEntry(self, motor_name, start_pos, final_pos, nb_triggers, trigger_interval, xia_spec_length):
        
        self._sendGlobalDictionaryBefore(motor_name, start_pos, final_pos, nb_triggers, trigger_interval, xia_spec_length)
        
        self.nexusconfig_device.Open()
        cmps = self.nexusconfig_device.AvailableComponents()
        cmp_list = []
        if "zebra_init" not in cmps:
            self.output("_openNxEntry: zebra not in configuration server")
        else:
            cmp_list.append("zebra_init")

        # Add component for the XIA.

        if "xia_init" not in cmps:
           self.output("_openNxEntry: xia not in configuration server")
        else:
            cmp_list.append("xia_init")

        # Add the default component

        if "default" not in cmps:
            self.output("_openNxEntry: default not in configuration server")
        else:
            cmp_list.append("default")

        self.nexusconfig_device.CreateConfiguration(cmp_list)
        xmlconfig = self.nexusconfig_device.XMLString
        self.nexuswriter_device.XMLSettings = str(xmlconfig)
#        try:
#            self.nexuswriter_device.OpenEntry()
#        except:
#            pass


        try:
            self.nexuswriter_device.OpenEntryAsynch()
        except:
            pass
        
        while self.nexuswriter_device.State() == PyTango.DevState.RUNNING:
            time.sleep(0.01)

        return 1


    def _closeNxFile(self):
        self.nexuswriter_device.CloseFile()
        return 1


    def _closeNxEntry(self):
        self._sendGlobalDictionaryAfter()
        self.nexuswriter_device.CloseEntry()
        return 1

    def _sendGlobalDictionaryBefore(self, motor_name, start_pos, final_pos, nb_triggers, trigger_interval, xia_spec_length):
        hsh = {}
        hshSub = {}
        hshSub['motor_name'] = str(motor_name)
        hshSub['start_pos'] = start_pos
        hshSub['final_pos'] = final_pos
        hshSub['nb_triggers'] = nb_triggers
        hshSub['sample_time'] = trigger_interval
        fmt = '%Y-%m-%dT%H:%M:%S.%f%z'
        hshSub['start_time'] = str(self.starttime.strftime(fmt))
        hshSub['title'] = ""
        hshSub['sample_name'] = ""
        hshSub['chemical_formula'] = ""
        hshSub['beamtime_id'] = ""
#        hshSub["encoder_pos"] = [dt for dt in self.zebra_data]
        hsh['data'] = hshSub
        self._setParameter( hsh)
        return 1

    def _sendGlobalDictionaryAfter(self):
        hsh = {}
        hshSub = {}
        amsterdam = pytz.timezone('Europe/Amsterdam')
        fmt = '%Y-%m-%dT%H:%M:%S.%f%z'
        starttime = amsterdam.localize(datetime.datetime.now())
        hshSub['end_time'] = str(starttime.strftime(fmt))
        hshSub['comments'] = "some comment"
        hsh['data'] = hshSub
        self._setParameter( hsh)
        return 1

    def _setParameter(self, hsh):
        jsondata = json.dumps( hsh)
        self.nexuswriter_device.JSONRecord = str(jsondata)
        return 1

    def _sendRecordToNxWriter(self, hsh):
        mstr = json.dumps( hsh)
        self.nexuswriter_device.Record(mstr)
        return 1

class cscan_zebra_xia_senv(Macro):
    """ Sets default environment variables """

    def run(self):
#        self.setEnv("MCSDevice", "haso107klx:10000/p09/mcs/exp.01")
#        self.output("Setting MCSDevice to ")
        self.setEnv("ZebraDevice", "p06/zebra/exp.01")
        self.output("Setting ZebraDevice to p06/zebra/exp.01")
        self.setEnv("XIADevice", "haspp06xmap:10000/p06/xia/p06.1")
        self.output("Setting XIADevice to hasp029rack:10000/test/xia/01")
        self.setEnv("CScanFileName", "/home/experiment/test_cscan_output")
        self.output("Setting CScanFileName to /home/experiment/test_cscan_output")
        self.setEnv("NeXusConfigDevice", "p06/nxsconfigserver/haspp06ctrl")
        self.output("Setting NeXusConfigDevice to p06/nxsconfigserver/haspp06ctrl")
        self.setEnv("NeXusWriterDevice", "p06/nxsdatawriter/haspp06ctrl")
        self.output("Setting NeXusWriterDevice to p06/nxsdatawriter/haspp06ctrl")
        self.setEnv("CScanID", 0)
        self.output("Setting CScanID to 0")
